### ISSUE TITLE
how to get session-id

### ISSUE THREAD

**Issue by wanghaisheng** [stevesajeev1/TikTok-Remixer#1]

**Comment by stevesajeev1** [comment]
To get it, log into your TikTok account and once you are on the page, press the F12 key on your keyboard to open developer tools. Then, go to Application > Storage > Cookies and find the value of the sessionid cookie. You should have something like this: `7a9f3c5d8f6e4b2a1c9d8e7f6a5b4c3d`

**Note that your TikTok sessionid cookie needs to be updated every 2 months.**
